Steel_FamilyHome_2F_MapScripts::
	.byte 0

Steel_Home_2F_PlayerSign::
	msgbox Steel_Home_2F_Text_Player, MSGBOX_SIGN
	end

Steel_Home_2F_KyleSign::
	msgbox Steel_Home_2F_Text_Kyle, MSGBOX_SIGN
	end

Steel_Home_2F_ParentsSign::
	msgbox Steel_Home_2F_Text_Parents, MSGBOX_SIGN
	end

Steel_Home_2F_Text_Player:
	.string "PLAYER'S ROOM$"

Steel_Home_2F_Text_Kyle:
	.string "KYLE'S ROOM\nNine minutes older, nine minutes louder.$"

Steel_Home_2F_Text_Parents:
	.string "LOGAN and MADISON'S ROOM\nOld trainers' rest.$"
