#ifndef GUARD_CONSTANTS_POKEMON_STEEL_H
#define GUARD_CONSTANTS_POKEMON_STEEL_H

// Saved opening progress. Append stages instead of renumbering existing saves.
#define STEEL_OPENING_ROLL_CALL 0
#define STEEL_OPENING_DISMISSED 1
#define STEEL_OPENING_HOME 2
#define STEEL_OPENING_CREEK_NEXT 3

#define STEEL_OPENING_RIDGE_HOME 4

// Appended stages: the original 0-4 values remain save-compatible.
#define STEEL_OPENING_ALUMINA_WALK 5
#define STEEL_OPENING_LEAVING_HOME 6
#define STEEL_OPENING_RIDGE_CREEK 7
#define STEEL_OPENING_CATCHING 8
#define STEEL_OPENING_WOODS_RETURN 9
#define STEEL_OPENING_RIDGE_RETURN 10
#define STEEL_OPENING_HOME_RETURN 11
#define STEEL_OPENING_STARTER_CHOICE 12
#define STEEL_OPENING_KYLE_BATTLE 13
#define STEEL_OPENING_KYLE_LEAVES 14
#define STEEL_OPENING_COMPLETE 15
#define STEEL_OPENING_TUTORIAL_RETRY 16

// Replace this roster when custom species are implemented; scripts stay intact.
#define STEEL_STARTER_NONE 0
#define STEEL_STARTER_CHOICE_POSSKIT 1
#define STEEL_STARTER_CHOICE_SHELDO 2
#define STEEL_STARTER_CHOICE_MIMBRI 3
#define STEEL_STARTER_POSSKIT SPECIES_ZIGZAGOON
#define STEEL_STARTER_SHELDO SPECIES_SANDSHREW
#define STEEL_STARTER_MIMBRI SPECIES_TAILLOW
#define STEEL_TUTORIAL_SPECIES STEEL_STARTER_MIMBRI
#define STEEL_LOGAN_BACK_PIC TRAINER_PIC_STEVEN

#define STEEL_REGISTRATION_NONE 0
#define STEEL_REGISTRATION_ACTIVE 1
#define STEEL_REGISTRATION_KYLE_DONE 2
#define STEEL_REGISTRATION_COMPLETE 3

#endif
